FROM python:3.9-slim
WORKDIR /app
ENV DB_HOST="127.0.0.1"
ENV DB_USER="app"
ENV DB_NAME="example"
RUN addgroup --system python && adduser --system --disabled-Password --ingroup python python && chown python:python /app
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update
COPY --chown=python:python . .
RUN pip3 install -r requirements.txt
EXPOSE 5000
CMD ["python", "not_tested_main.py"]
